---
  # site.yml for the Ansible-md5check playbook

  - name: ensure the app directory is present
    file:
      path: "{{ deploy_dir }}"
      state: directory
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"
      mode: 0755

  - name: download the file
    get_url:
      url: "{{ deploy_app }}"
      dest: "{{ deploy_dir }}"
